name: Cypress Tests

on: workflow_dispatch

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
            build: npm run build
            start: npm start
            browser: chrome
